# permissions for end users to view rabbitqueues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitqueue-viewer-role
rules:
- apiGroups:
  - queue.frestyle
  resources:
  - rabbitqueues
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - queue.frestyle
  resources:
  - rabbitqueues/status
  verbs:
  - get
